
CC = g++

# SRC = ${wildcard *.cpp}

SRC = main.cpp

TARGET = test.out

FLAGS = -g -Wall -lglfw -lglad -lGL -lstb

all:${SRC}
	${CC} -o ${TARGET} ${SRC} ${FLAGS} 
x:
	${CC} -o a.out algo_grow.cpp ${FLAGS} -lglut -lGLU -lGL